modules_dir = "artifacts/"

[[module]]
name = "curl_adapter"
max_heap_size = "128 MiB"
logger_enabled = true

[module.mounted_binaries]
curl = "/usr/bin/curl"

[[module]]
name = "multi_provider_query"
max_heap_size = "10 KiB"
logger_enabled = true
